version: '3.1'
services:
  chat-app:
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    environment:
      - SECRET=${SECRET:-my-awesome-secret}
    build: .
    command: npm run start:${ENV:-dev}
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT:-3200}:80
    links:
      - redis

  redis:
    image: redis:5.0.7-alpine
    ports:
      - ${REDISPORT:-6379}:6379
